
import { Capacitacao } from '../types';

export const MOCK_CAPACITACOES: Capacitacao[] = [
  {
    id: 1,
    servidor: 'Ana Silva',
    matricula: '12345',
    uorg: 'DITEC-I',
    evento: 'Introdução ao React com TypeScript',
    status: 'Concluído',
    carga_horaria: 40,
    instituicao_promotora: 'Escola Nacional de Administração Pública (ENAP)',
    modalidade: 'EAD',
    data_inicio: '2023-03-15',
    data_termino: '2023-04-10',
    valor_evento: 500.00,
    data_criacao: new Date().toISOString(),
    data_atualizacao: new Date().toISOString()
  },
  {
    id: 2,
    servidor: 'Bruno Costa',
    matricula: '67890',
    uorg: 'DITEC-VII',
    evento: 'Gestão de Projetos Ágeis com Scrum',
    status: 'Concluído',
    carga_horaria: 24,
    instituicao_promotora: 'Fundação Getúlio Vargas (FGV)',
    modalidade: 'Presencial',
    data_inicio: '2023-05-20',
    data_termino: '2023-05-22',
    valor_evento: 1200.50,
    data_criacao: new Date().toISOString(),
    data_atualizacao: new Date().toISOString()
  },
  {
    id: 3,
    servidor: 'Carlos Souza',
    matricula: '11223',
    uorg: 'DITEC-I',
    evento: 'Segurança da Informação para Gestores',
    status: 'Em andamento',
    carga_horaria: 16,
    instituicao_promotora: 'Serpro',
    modalidade: 'Híbrido',
    data_inicio: '2024-07-25',
    data_termino: '2024-08-05',
    valor_evento: 800.00,
    data_criacao: new Date().toISOString(),
    data_atualizacao: new Date().toISOString()
  },
  {
    id: 4,
    servidor: 'Daniela Lima',
    matricula: '44556',
    uorg: 'DITEC-III',
    evento: 'Python para Análise de Dados',
    status: 'Concluído',
    carga_horaria: 60,
    instituicao_promotora: 'Alura Cursos',
    modalidade: 'EAD',
    data_inicio: '2023-09-01',
    data_termino: '2023-10-15',
    valor_evento: 750.00,
    data_criacao: new Date().toISOString(),
    data_atualizacao: new Date().toISOString()
  },
  {
    id: 5,
    servidor: 'Eduardo Pereira',
    matricula: '77889',
    uorg: 'DITEC-VII',
    evento: 'Liderança e Gestão de Equipes',
    status: 'Pendente',
    carga_horaria: 32,
    instituicao_promotora: 'ENAP',
    modalidade: 'Presencial',
    data_inicio: '2024-09-10',
    data_termino: '2024-09-14',
    valor_evento: 950.00,
    data_criacao: new Date().toISOString(),
    data_atualizacao: new Date().toISOString()
  },
  {
    id: 6,
    servidor: 'Fernanda Almeida',
    matricula: '99001',
    uorg: 'DITEC-V',
    evento: 'Comunicação Não-Violenta no Ambiente de Trabalho',
    status: 'Concluído',
    carga_horaria: 8,
    instituicao_promotora: 'SENAC',
    modalidade: 'EAD',
    data_inicio: '2024-02-10',
    data_termino: '2024-02-11',
    valor_evento: 250.00,
    data_criacao: new Date().toISOString(),
    data_atualizacao: new Date().toISOString()
  }
];
